server:
  port: 8888
spring:
  cloud:
    config:
      server:
        composite:
          - type: native
            search-locations: classpath:/shared
        bootstrap: true
  profiles:
    active: composite
  security:
    user:
      password: ahmadali1976
