server:
  port: 8220
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/post_db
    username: postgres
    password: ahmadali1976
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create

